
URL_DEVICELIST = '/ISAPI/ContentMgmt/DeviceMgmt/deviceList'
URL_CAPABILITIES = '/ISAPI/System/capabilities'
URL_RemoteControl = '/ISAPI/AccessControl/RemoteControl/door/:id'
URL_RECORD_USER = '/ISAPI/AccessControl/UserInfo/Record'
URL_SEARCH_USER = '/ISAPI/AccessControl/UserInfo/Search'
URL_RECORD_CARD = '/ISAPI/AccessControl/CardInfo/Record'
URL_SEARCH_CARD = '/ISAPI/AccessControl/CardInfo/Search'
URL_DELETE_CARD = '/ISAPI/AccessControl/CardInfo/Delete'
URL_FaceDataRecord = '/ISAPI/Intelligent/FDLib/FaceDataRecord'
URL_FDSearch = '/ISAPI/Intelligent/FDLib/FDSearch'
URL_AcsEvent = '/ISAPI/AccessControl/AcsEvent'
